### ISSUE TITLE
[Feature Request] Clear device names

### ISSUE THREAD

**Issue by Donkere-vader** [adaxi/audio-output-switcher#13]
Hey first of all nice work! works great!

My idea:
Change the name of the devices in the list.

Cuz now my speakers are named: "GP106 High defenition audio controller"  and my headset is called: "Familly 17h bla bla...."
And I think you can agree that that is not very clear or intuitive.

So It would be nice if I could rename to as what they would show up as in the list.

So that my audio  output devices would be:
- speakers
- Headset

In stead of the earlier named names.

Edit: clarification

**Comment by gbrld** [comment]
You'll need to rename your devices directly in PulseAudio, here are the general steps:

>Find device hardware ids:
```
aplay -l
```

>Manually configure your devices in "/etc/pulse/default.pa" using the hardware ids from the first step as "hw:x,y", where 'x' is the card number and 'y' is the device number.  Place this at the top of the file, before ".fail":
```
load-module module-alsa-sink device="hw:0,0" sink_name=headphones sink_properties=device.description='My\ Speakers'
load-module module-alsa-sink device="hw:0,1" sink_name=headphones sink_properties=device.description='My\ Headphones'
```

>If you are getting duplicates of the ones you added, you can disable the automatic detection by commenting these two lines in that same file:
```
#load-module module-udev-detect
#load-module module-detect
```

**Comment by adaxi** [comment]
@Donkere-vader,

Although a great feature request, it seems really complex to implement, and I would like to keep this plugin as simple as possible.

Is there somewhere a mapping that would allow us to know what kind of device is actually connected?
What about if the user has two devices of the same kind? How would they know which one is which?

If a simple solution is found, I'll accept the pull request. In the mean time, it looks like the solution provided by @gbrld might solve your issue.
