### ISSUE TITLE
GNOME 41 Support

### ISSUE THREAD

**Issue by FlyinPancake** [adaxi/audio-output-switcher#24]
The extensions is greyed out for gnome 41. 
I don't know how I should go on updating it, but I'd like to help any way possible.

**Comment by frosth555** [comment]
Just edit metadata.json and add "41" in "shell-version" section. It works for me.

**Comment by adaxi** [comment]
Added support for Gnome 41.

**Comment by kurobeats** [comment]
Is there a delay in being published to https://extensions.gnome.org/? I note that it only goes to gnome 40 there.
