### ISSUE TITLE
GNOME 41 Support

### ISSUE THREAD

**Issue by kurobeats** [adaxi/audio-output-switcher#27]
No longer installable via https://extensions.gnome.org/extension/751/audio-output-switcher/ if Gnome 41 is used

**Comment by ElijahLynn** [comment]
Was disabled for me on recent update too:
![image](https://user-images.githubusercontent.com/1504756/144650038-0a9b005f-318b-4c36-af40-4725161197c0.png)

**Comment by idkCpp** [comment]
Last commit on master was 232a122 which added 41 to the versions. But this seems not to be available via extensions.gnome.org
But I don't know how this works :man_shrugging:

**Comment by idkCpp** [comment]
Appears to be resolved

**Comment by adaxi** [comment]
Yes, sorry for the delays, the extension was not approved first time around. Only had some time now to clean it up.
