### ISSUE TITLE
Add the option to select INPUTs as well

### ISSUE THREAD

**Issue by ivan-pinatti** [adaxi/audio-output-switcher#9]
Hi,

Congrats for the plugin, I use it for a few years already and it works like a charm. However, it would be nice to also have the option to select the input in the same way. Would you be able to add this functionality to the plugin?

Thank you and have a great week. :)

**Comment by chaseadam** [comment]
Have you tried the "audio-input-switcher" mentioned in the README.md?
> Most importantly this extension is as simple as possible. Therefore it does not include an input switcher or similar. See Audio-Input-Switcher (https://github.com/anduchs/audio-input-switcher) extension for microphone selection.

**Comment by ivan-pinatti** [comment]
Hi @chaseadam,

Great! It worked like a charm. :)

They could merge both plugins into just one.

Cheers!

**Comment by ewjoachim** [comment]
Hello :) Just a side note: https://github.com/anduchs/audio-input-switcher has been abandoned and in incompatible with recent Gnome versions. It was really nice to have the same UI for inputs and output. If you ever plan to reconsider, it would be highly appreciated. That said, I completly understand if you don't want to add more of a burden than what you already do with the output switcher, and thanks for that.
